apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contact-backend
  template:
    metadata:
      labels:
        app: contact-backend
    spec:
      containers:
      - name: backend
        image: your-dockerhub-username/contact-backend:latest
        ports:
        - containerPort: 3001