apiVersion: v1
kind: Service
metadata:
  name: contact-backend-service
spec:
  type: NodePort
  selector:
    app: contact-backend
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 32001  # Optional: expose on a known port
